[project]
name = "backend"
version = "0.1.0"
description = "backend for news"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "openai>=1.93.0",
    "reader>=3.18",
    "selenium>=4.33.0",
]
